version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post-build

artifacts:
  files:
    - target/myAtmService-1.0.0-RELEASE.jar