INSERT INTO CURRENCY (ID, CURRENCY_TYPE, CURRENCY_VALUE, CURRENCY_COUNT) VALUES ('1', 'THOUSAND', 1000, 20);
INSERT INTO CURRENCY (ID, CURRENCY_TYPE, CURRENCY_VALUE, CURRENCY_COUNT) VALUES ('2', 'FIVE_HUNDRED', 500, 20);
INSERT INTO CURRENCY (ID, CURRENCY_TYPE, CURRENCY_VALUE, CURRENCY_COUNT) VALUES ('3', 'ONE_HUNDRED', 100, 20);
INSERT INTO CURRENCY (ID, CURRENCY_TYPE, CURRENCY_VALUE, CURRENCY_COUNT) VALUES ('4', 'FIFTY', 50, 20);
INSERT INTO CURRENCY (ID, CURRENCY_TYPE, CURRENCY_VALUE, CURRENCY_COUNT) VALUES ('5', 'TWENTY', 20, 20);